[package]
name = "reflicate"
version = "0.2.0"
edition = "2021"
description = "Deduplicate data by creating reflinks between identical files"
readme = "README.md"
license = "MIT"
repository = "https://github.com/gblach/reflicate"
keywords = ["cli", "deduplication", "filesystem", "reflink", "utility"]
categories = ["command-line-utilities", "filesystem"]

[dependencies]
argh = "0.1"
blake3 = "1.3"
cdb = "0.6"
fiemap = "0.1"
getrandom = "0.2"
libc = "0.2"
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
