[package]
name = "reflicate"
version = "0.1.0"
edition = "2021"
description = "Deduplicate data by creating reflinks between identical files"
license = "MIT"
repository = "https://github.com/gblach/reflicate"

[dependencies]
argh = "0.1"
blake3 = "1.3"
cdb = "0.6"
getrandom = "0.2"
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
cc = "1.0"
